# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@2.1.1

executors:
    default:
        description: The official CircleCI CIMG Python Docker image.
        docker:
            - image: cimg/python:<< parameters.tag >>
        parameters:
            tag:
                default: "3.8"
                description: The `cimg/python` Docker image version tag.
                type: string

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  lint:
    executor:
      name: default
      tag: "3.9"

    steps:
      - checkout
      - run:
          name: Install tox
          command: pip install tox
      - run:
          name: Run linters
          command: tox -e lint,type
  test:
    parameters:
      py_version:
        type: string
        default: "3.8"
    executor:
      name: default
      tag: << parameters.py_version >>
    steps:
      - checkout
      - run:
          name: Install tox
          command: pip install tox
      - run:
          name: Run tests
          command: tox -e py

# Invoke jobs via workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  ci:
    jobs:
      - lint
      - test:
          matrix:
            parameters:
              py_version:
                - "3.8"
                - "3.9"
                - "3.10"
                - "3.11"
